import os
import sys
import datetime
from socket import gethostname
sys.path.append("/Users/jason/Documents/ProvenanceTools/prov")
import prov.model as prov
from prov.model import Namespace, PROV
EX=Namespace("ex","http://www.example.com/")
g = prov.ProvBundle()
g.entity('matlabbatch')
g.entity('matlabbatch1')
g.used('matlabbatch','matlabbatch1')
g.entity('matlabbatch1.spm',{'prov:type':'bundle','prov:label':'spm','spm:structpath':'matlabbatch1'})
g.used('matlabbatch1','matlabbatch1.spm')
g.entity('matlabbatch1.spm.temporal',{'prov:type':'bundle','prov:label':'temporal','spm:structpath':'matlabbatch1.spm'})
g.used('matlabbatch1.spm','matlabbatch1.spm.temporal')
g.entity('matlabbatch1.spm.temporal.st',{'prov:type':'bundle','prov:label':'st','spm:structpath':'matlabbatch1.spm.temporal'})
g.used('matlabbatch1.spm.temporal','matlabbatch1.spm.temporal.st')
g.entity('matlabbatch1.spm.temporal.st.scans',{'prov:type':'bundle','prov:label':'scans','spm:structpath':'matlabbatch1.spm.temporal.st'})
g.used('matlabbatch1.spm.temporal.st','matlabbatch1.spm.temporal.st.scans')
g.entity('matlabbatch1.spm.temporal.st.nslices',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.temporal.st','prov:label':'nslices','prov:value':'41'})
g.used('matlabbatch1.spm.temporal.st','matlabbatch1.spm.temporal.st.nslices')
g.entity('matlabbatch1.spm.temporal.st.tr',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.temporal.st','prov:label':'tr','prov:value':'2'})
g.used('matlabbatch1.spm.temporal.st','matlabbatch1.spm.temporal.st.tr')
g.entity('matlabbatch1.spm.temporal.st.ta',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.temporal.st','prov:label':'ta','prov:value':'1.9512'})
g.used('matlabbatch1.spm.temporal.st','matlabbatch1.spm.temporal.st.ta')
g.entity('matlabbatch1.spm.temporal.st.so',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.temporal.st','prov:label':'so','prov:value':'[ 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]'})
g.used('matlabbatch1.spm.temporal.st','matlabbatch1.spm.temporal.st.so')
g.entity('matlabbatch1.spm.temporal.st.refslice',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.temporal.st','prov:label':'refslice','prov:value':'20'})
g.used('matlabbatch1.spm.temporal.st','matlabbatch1.spm.temporal.st.refslice')
g.entity('matlabbatch1.spm.temporal.st.prefix',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.temporal.st','prov:label':'prefix','prov:value':'a'})
g.used('matlabbatch1.spm.temporal.st','matlabbatch1.spm.temporal.st.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/aECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.temporal.st.prefix','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.temporal.st.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/aECF_r1_P00004218_S0001.nii','matlabbatch1.spm.temporal.st.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/aECF_r2_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.temporal.st.prefix','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.temporal.st.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/aECF_r2_P00004218_S0001.nii','matlabbatch1.spm.temporal.st.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/ECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.temporal.st.scans','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.temporal.st.scans'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/ECF_r1_P00004218_S0001.nii','matlabbatch1.spm.temporal.st.scans')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/ECF_r2_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.temporal.st.scans','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.temporal.st.scans'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/ECF_r2_P00004218_S0001.nii','matlabbatch1.spm.temporal.st.scans')
with open('/Users/jason/Documents/ProvenanceTools/SPMprovenance/OutputFiles/TestSliceTimeRECURSIVE.provn', 'wt') as fp:fp.writelines(g.get_provn())
