import os
import sys
import datetime
from socket import gethostname
sys.path.append("/Users/jason/Documents/ProvenanceTools/prov")
import prov.model as prov
from prov.model import Namespace, PROV
EX=Namespace("ex","http://www.example.com/")
g = prov.ProvBundle()
g.entity('matlabbatch')
g.entity('matlabbatch1')
g.used('matlabbatch','matlabbatch1')
g.entity('matlabbatch1.spm',{'prov:type':'bundle','prov:label':'spm','spm:structpath':'matlabbatch1'})
g.used('matlabbatch1','matlabbatch1.spm')
g.entity('matlabbatch1.spm.spatial',{'prov:type':'bundle','prov:label':'spatial','spm:structpath':'matlabbatch1.spm'})
g.used('matlabbatch1.spm','matlabbatch1.spm.spatial')
g.entity('matlabbatch1.spm.spatial.smooth',{'prov:type':'bundle','prov:label':'smooth','spm:structpath':'matlabbatch1.spm.spatial'})
g.used('matlabbatch1.spm.spatial','matlabbatch1.spm.spatial.smooth')
g.entity('matlabbatch1.spm.spatial.smooth.data',{'prov:type':'bundle','prov:label':'data','spm:structpath':'matlabbatch1.spm.spatial.smooth'})
g.used('matlabbatch1.spm.spatial.smooth','matlabbatch1.spm.spatial.smooth.data')
g.entity('matlabbatch1.spm.spatial.smooth.fwhm',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.smooth','prov:label':'fwhm','prov:value':'[ 8 8 8]'})
g.used('matlabbatch1.spm.spatial.smooth','matlabbatch1.spm.spatial.smooth.fwhm')
g.entity('matlabbatch1.spm.spatial.smooth.dtype',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.smooth','prov:label':'dtype','prov:value':'0'})
g.used('matlabbatch1.spm.spatial.smooth','matlabbatch1.spm.spatial.smooth.dtype')
g.entity('matlabbatch1.spm.spatial.smooth.im',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.smooth','prov:label':'im','prov:value':'0'})
g.used('matlabbatch1.spm.spatial.smooth','matlabbatch1.spm.spatial.smooth.im')
g.entity('matlabbatch1.spm.spatial.smooth.prefix',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.smooth','prov:label':'prefix','prov:value':'s'})
g.used('matlabbatch1.spm.spatial.smooth','matlabbatch1.spm.spatial.smooth.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/swaECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.smooth.prefix','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.smooth.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/swaECF_r1_P00004218_S0001.nii','matlabbatch1.spm.spatial.smooth.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/swmeanaECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.smooth.prefix','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.smooth.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/swmeanaECF_r1_P00004218_S0001.nii','matlabbatch1.spm.spatial.smooth.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/swaECF_r2_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.smooth.prefix','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.smooth.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/swaECF_r2_P00004218_S0001.nii','matlabbatch1.spm.spatial.smooth.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/waECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.smooth.data','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.smooth.data'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/waECF_r1_P00004218_S0001.nii','matlabbatch1.spm.spatial.smooth.data')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/wmeanaECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.smooth.data','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.smooth.data'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/wmeanaECF_r1_P00004218_S0001.nii','matlabbatch1.spm.spatial.smooth.data')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/waECF_r2_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.smooth.data','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.smooth.data'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/waECF_r2_P00004218_S0001.nii','matlabbatch1.spm.spatial.smooth.data')
with open('/Users/jason/Documents/ProvenanceTools/SPMprovenance/OutputFiles/TestSmoothRECURSIVE.provn', 'wt') as fp:fp.writelines(g.get_provn())
