import os
import sys
import datetime
from socket import gethostname
sys.path.append("/Users/jason/Documents/ProvenanceTools/prov")
import prov.model as prov
from prov.model import Namespace, PROV
EX=Namespace("ex","http://www.example.com/")
g = prov.ProvBundle()
g.entity('matlabbatch')
g.entity('matlabbatch1')
g.used('matlabbatch','matlabbatch1')
g.entity('matlabbatch1.spm',{'prov:type':'bundle','prov:label':'spm','spm:structpath':'matlabbatch1'})
g.used('matlabbatch1','matlabbatch1.spm')
g.entity('matlabbatch1.spm.spatial',{'prov:type':'bundle','prov:label':'spatial','spm:structpath':'matlabbatch1.spm'})
g.used('matlabbatch1.spm','matlabbatch1.spm.spatial')
g.entity('matlabbatch1.spm.spatial.coreg',{'prov:type':'bundle','prov:label':'coreg','spm:structpath':'matlabbatch1.spm.spatial'})
g.used('matlabbatch1.spm.spatial','matlabbatch1.spm.spatial.coreg')
g.entity('matlabbatch1.spm.spatial.coreg.estimate',{'prov:type':'bundle','prov:label':'estimate','spm:structpath':'matlabbatch1.spm.spatial.coreg'})
g.used('matlabbatch1.spm.spatial.coreg','matlabbatch1.spm.spatial.coreg.estimate')
g.entity('matlabbatch1.spm.spatial.coreg.estimate.ref',{'prov:type':'bundle','prov:label':'ref','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate'})
g.used('matlabbatch1.spm.spatial.coreg.estimate','matlabbatch1.spm.spatial.coreg.estimate.ref')
g.entity('matlabbatch1.spm.spatial.coreg.estimate.source',{'prov:type':'bundle','prov:label':'source','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate'})
g.used('matlabbatch1.spm.spatial.coreg.estimate','matlabbatch1.spm.spatial.coreg.estimate.source')
g.entity('matlabbatch1.spm.spatial.coreg.estimate.other',{'prov:type':'bundle','prov:label':'other','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate'})
g.used('matlabbatch1.spm.spatial.coreg.estimate','matlabbatch1.spm.spatial.coreg.estimate.other')
g.entity('matlabbatch1.spm.spatial.coreg.estimate.eoptions',{'prov:type':'bundle','prov:label':'eoptions','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate'})
g.used('matlabbatch1.spm.spatial.coreg.estimate','matlabbatch1.spm.spatial.coreg.estimate.eoptions')
g.entity('matlabbatch1.spm.spatial.coreg.estimate.eoptions.cost_fun',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate.eoptions','prov:label':'cost_fun','prov:value':'nmi'})
g.used('matlabbatch1.spm.spatial.coreg.estimate.eoptions','matlabbatch1.spm.spatial.coreg.estimate.eoptions.cost_fun')
g.entity('matlabbatch1.spm.spatial.coreg.estimate.eoptions.sep',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate.eoptions','prov:label':'sep','prov:value':'[ 4 2]'})
g.used('matlabbatch1.spm.spatial.coreg.estimate.eoptions','matlabbatch1.spm.spatial.coreg.estimate.eoptions.sep')
g.entity('matlabbatch1.spm.spatial.coreg.estimate.eoptions.tol',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate.eoptions','prov:label':'tol','prov:value':'[ 0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001]'})
g.used('matlabbatch1.spm.spatial.coreg.estimate.eoptions','matlabbatch1.spm.spatial.coreg.estimate.eoptions.tol')
g.entity('matlabbatch1.spm.spatial.coreg.estimate.eoptions.fwhm',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate.eoptions','prov:label':'fwhm','prov:value':'[ 7 7]'})
g.used('matlabbatch1.spm.spatial.coreg.estimate.eoptions','matlabbatch1.spm.spatial.coreg.estimate.eoptions.fwhm')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/T1/mT1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.coreg.estimate.ref','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate.ref'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/T1/mT1_P00004218_S0001.nii','matlabbatch1.spm.spatial.coreg.estimate.ref')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/meanaECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.coreg.estimate.source','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate.source'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/meanaECF_r1_P00004218_S0001.nii','matlabbatch1.spm.spatial.coreg.estimate.source')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/aECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.coreg.estimate.other','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate.other'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/aECF_r1_P00004218_S0001.nii','matlabbatch1.spm.spatial.coreg.estimate.other')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/aECF_r2_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.coreg.estimate.other','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.coreg.estimate.other'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/aECF_r2_P00004218_S0001.nii','matlabbatch1.spm.spatial.coreg.estimate.other')
with open('/Users/jason/Documents/ProvenanceTools/SPMprovenance/OutputFiles/TestCoRegPart2RECURSIVE.provn', 'wt') as fp:fp.writelines(g.get_provn())
