import os
import sys
import datetime
from socket import gethostname
sys.path.append("/Users/jason/Documents/ProvenanceTools/prov")
import prov.model as prov
from prov.model import Namespace, PROV
EX=Namespace("ex","http://www.example.com/")
g = prov.ProvBundle()
g.entity('matlabbatch')
g.entity('matlabbatch1')
g.used('matlabbatch','matlabbatch1')
g.entity('matlabbatch1.spm',{'prov:type':'bundle','prov:label':'spm','spm:structpath':'matlabbatch1'})
g.used('matlabbatch1','matlabbatch1.spm')
g.entity('matlabbatch1.spm.spatial',{'prov:type':'bundle','prov:label':'spatial','spm:structpath':'matlabbatch1.spm'})
g.used('matlabbatch1.spm','matlabbatch1.spm.spatial')
g.entity('matlabbatch1.spm.spatial.realign',{'prov:type':'bundle','prov:label':'realign','spm:structpath':'matlabbatch1.spm.spatial'})
g.used('matlabbatch1.spm.spatial','matlabbatch1.spm.spatial.realign')
g.entity('matlabbatch1.spm.spatial.realign.estwrite',{'prov:type':'bundle','prov:label':'estwrite','spm:structpath':'matlabbatch1.spm.spatial.realign'})
g.used('matlabbatch1.spm.spatial.realign','matlabbatch1.spm.spatial.realign.estwrite')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.data',{'prov:type':'bundle','prov:label':'data','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite'})
g.used('matlabbatch1.spm.spatial.realign.estwrite','matlabbatch1.spm.spatial.realign.estwrite.data')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.eoptions',{'prov:type':'bundle','prov:label':'eoptions','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite'})
g.used('matlabbatch1.spm.spatial.realign.estwrite','matlabbatch1.spm.spatial.realign.estwrite.eoptions')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.eoptions.quality',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.eoptions','prov:label':'quality','prov:value':'0.9'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.eoptions','matlabbatch1.spm.spatial.realign.estwrite.eoptions.quality')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.eoptions.sep',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.eoptions','prov:label':'sep','prov:value':'4'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.eoptions','matlabbatch1.spm.spatial.realign.estwrite.eoptions.sep')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.eoptions.fwhm',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.eoptions','prov:label':'fwhm','prov:value':'5'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.eoptions','matlabbatch1.spm.spatial.realign.estwrite.eoptions.fwhm')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.eoptions.rtm',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.eoptions','prov:label':'rtm','prov:value':'1'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.eoptions','matlabbatch1.spm.spatial.realign.estwrite.eoptions.rtm')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.eoptions.interp',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.eoptions','prov:label':'interp','prov:value':'2'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.eoptions','matlabbatch1.spm.spatial.realign.estwrite.eoptions.interp')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.eoptions.wrap',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.eoptions','prov:label':'wrap','prov:value':'[ 0 0 0]'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.eoptions','matlabbatch1.spm.spatial.realign.estwrite.eoptions.wrap')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.eoptions.weight',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.eoptions','prov:label':'weight','prov:value':''})
g.used('matlabbatch1.spm.spatial.realign.estwrite.eoptions','matlabbatch1.spm.spatial.realign.estwrite.eoptions.weight')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.roptions',{'prov:type':'bundle','prov:label':'roptions','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite'})
g.used('matlabbatch1.spm.spatial.realign.estwrite','matlabbatch1.spm.spatial.realign.estwrite.roptions')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.roptions.which',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.roptions','prov:label':'which','prov:value':'[ 0 1]'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.roptions','matlabbatch1.spm.spatial.realign.estwrite.roptions.which')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.roptions.interp',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.roptions','prov:label':'interp','prov:value':'4'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.roptions','matlabbatch1.spm.spatial.realign.estwrite.roptions.interp')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.roptions.wrap',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.roptions','prov:label':'wrap','prov:value':'[ 0 0 0]'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.roptions','matlabbatch1.spm.spatial.realign.estwrite.roptions.wrap')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.roptions.mask',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.roptions','prov:label':'mask','prov:value':'1'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.roptions','matlabbatch1.spm.spatial.realign.estwrite.roptions.mask')
g.entity('matlabbatch1.spm.spatial.realign.estwrite.roptions.prefix',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.roptions','prov:label':'prefix','prov:value':'r'})
g.used('matlabbatch1.spm.spatial.realign.estwrite.roptions','matlabbatch1.spm.spatial.realign.estwrite.roptions.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/raECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.realign.estwrite.roptions.prefix','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.roptions.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/raECF_r1_P00004218_S0001.nii','matlabbatch1.spm.spatial.realign.estwrite.roptions.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/raECF_r2_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.realign.estwrite.roptions.prefix','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.roptions.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/raECF_r2_P00004218_S0001.nii','matlabbatch1.spm.spatial.realign.estwrite.roptions.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/aECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.realign.estwrite.data','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.data'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/aECF_r1_P00004218_S0001.nii','matlabbatch1.spm.spatial.realign.estwrite.data')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/aECF_r2_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.realign.estwrite.data','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.realign.estwrite.data'})
g.used('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/aECF_r2_P00004218_S0001.nii','matlabbatch1.spm.spatial.realign.estwrite.data')
with open('/Users/jason/Documents/ProvenanceTools/SPMprovenance/OutputFiles/TestRealignRECURSIVE.provn', 'wt') as fp:fp.writelines(g.get_provn())
