loadlibrary('/share/data/data9/jason/SPM_Provenance/INCF-ProvenanceLibrary-cb1478d/src/libneuroprov.so','/share/data/data9/jason/SPM_Provenance/INCF-ProvenanceLibrary-cb1478d/src/provenance.h')
loadlibrary('/share/data/data9/jason/SPM_Provenance/INCF-ProvenanceLibrary-cb1478d/src/libneuroprov.so','/share/data/data9/jason/SPM_Provenance/INCF-ProvenanceLibrary-cb1478d/src/neuroprovenance.h')
%libfunctionsview libneuroprov
libfunctionsview libneuroprov


% Create the account

% Create the process
% Create some artifacts

% Create an agent
% Dependencies
    % used
    % was generated by
    % was derived from
    % was controlled by