import os
import sys
import datetime
from socket import gethostname
sys.path.append("/Users/jason/Documents/ProvenanceTools/prov")
import prov.model as prov
from prov.model import Namespace, PROV
EX=Namespace("ex","http://www.example.com/")
g = prov.ProvBundle()
g.entity('matlabbatch')
g.entity('matlabbatch1')
g.used('matlabbatch','matlabbatch1')
g.entity('matlabbatch1.spm',{'prov:type':'bundle','prov:label':'spm','spm:structpath':'matlabbatch1'})
g.used('matlabbatch1','matlabbatch1.spm')
g.entity('matlabbatch1.spm.spatial',{'prov:type':'bundle','prov:label':'spatial','spm:structpath':'matlabbatch1.spm'})
g.used('matlabbatch1.spm','matlabbatch1.spm.spatial')
g.entity('matlabbatch1.spm.spatial.preproc',{'prov:type':'bundle','prov:label':'preproc','spm:structpath':'matlabbatch1.spm.spatial'})
g.used('matlabbatch1.spm.spatial','matlabbatch1.spm.spatial.preproc')
g.entity('matlabbatch1.spm.spatial.preproc.data',{'prov:type':'bundle','prov:label':'data','spm:structpath':'matlabbatch1.spm.spatial.preproc'})
g.used('matlabbatch1.spm.spatial.preproc','matlabbatch1.spm.spatial.preproc.data')
g.entity('matlabbatch1.spm.spatial.preproc.output',{'prov:type':'bundle','prov:label':'output','spm:structpath':'matlabbatch1.spm.spatial.preproc'})
g.used('matlabbatch1.spm.spatial.preproc','matlabbatch1.spm.spatial.preproc.output')
g.entity('matlabbatch1.spm.spatial.preproc.output.GM',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.output','prov:label':'GM','prov:value':'[ 1 1 1]'})
g.used('matlabbatch1.spm.spatial.preproc.output','matlabbatch1.spm.spatial.preproc.output.GM')
g.entity('matlabbatch1.spm.spatial.preproc.output.WM',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.output','prov:label':'WM','prov:value':'[ 1 1 1]'})
g.used('matlabbatch1.spm.spatial.preproc.output','matlabbatch1.spm.spatial.preproc.output.WM')
g.entity('matlabbatch1.spm.spatial.preproc.output.CSF',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.output','prov:label':'CSF','prov:value':'[ 1 1 1]'})
g.used('matlabbatch1.spm.spatial.preproc.output','matlabbatch1.spm.spatial.preproc.output.CSF')
g.entity('matlabbatch1.spm.spatial.preproc.output.biascor',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.output','prov:label':'biascor','prov:value':'1'})
g.used('matlabbatch1.spm.spatial.preproc.output','matlabbatch1.spm.spatial.preproc.output.biascor')
g.entity('matlabbatch1.spm.spatial.preproc.output.cleanup',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.output','prov:label':'cleanup','prov:value':'0'})
g.used('matlabbatch1.spm.spatial.preproc.output','matlabbatch1.spm.spatial.preproc.output.cleanup')
g.entity('matlabbatch1.spm.spatial.preproc.opts',{'prov:type':'bundle','prov:label':'opts','spm:structpath':'matlabbatch1.spm.spatial.preproc'})
g.used('matlabbatch1.spm.spatial.preproc','matlabbatch1.spm.spatial.preproc.opts')
g.entity('matlabbatch1.spm.spatial.preproc.opts.tpm',{'prov:type':'bundle','prov:label':'tpm','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts'})
g.used('matlabbatch1.spm.spatial.preproc.opts','matlabbatch1.spm.spatial.preproc.opts.tpm')
g.entity('matlabbatch1.spm.spatial.preproc.opts.ngaus',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts','prov:label':'ngaus','prov:value':'[ 2; 2; 2; 4]'})
g.used('matlabbatch1.spm.spatial.preproc.opts','matlabbatch1.spm.spatial.preproc.opts.ngaus')
g.entity('matlabbatch1.spm.spatial.preproc.opts.regtype',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts','prov:label':'regtype','prov:value':'mni'})
g.used('matlabbatch1.spm.spatial.preproc.opts','matlabbatch1.spm.spatial.preproc.opts.regtype')
g.entity('matlabbatch1.spm.spatial.preproc.opts.warpreg',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts','prov:label':'warpreg','prov:value':'1'})
g.used('matlabbatch1.spm.spatial.preproc.opts','matlabbatch1.spm.spatial.preproc.opts.warpreg')
g.entity('matlabbatch1.spm.spatial.preproc.opts.warpco',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts','prov:label':'warpco','prov:value':'25'})
g.used('matlabbatch1.spm.spatial.preproc.opts','matlabbatch1.spm.spatial.preproc.opts.warpco')
g.entity('matlabbatch1.spm.spatial.preproc.opts.biasreg',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts','prov:label':'biasreg','prov:value':'0.0001'})
g.used('matlabbatch1.spm.spatial.preproc.opts','matlabbatch1.spm.spatial.preproc.opts.biasreg')
g.entity('matlabbatch1.spm.spatial.preproc.opts.biasfwhm',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts','prov:label':'biasfwhm','prov:value':'60'})
g.used('matlabbatch1.spm.spatial.preproc.opts','matlabbatch1.spm.spatial.preproc.opts.biasfwhm')
g.entity('matlabbatch1.spm.spatial.preproc.opts.samp',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts','prov:label':'samp','prov:value':'3'})
g.used('matlabbatch1.spm.spatial.preproc.opts','matlabbatch1.spm.spatial.preproc.opts.samp')
g.entity('matlabbatch1.spm.spatial.preproc.opts.msk',{'prov:type':'bundle','prov:label':'msk','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts'})
g.used('matlabbatch1.spm.spatial.preproc.opts','matlabbatch1.spm.spatial.preproc.opts.msk')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/c1P00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.output','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.output'})
g.wasDerivedFrom('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/c1P00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.output')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/mwc1P00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.output','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.output'})
g.wasDerivedFrom('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/mwc1P00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.output')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/wc1P00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.output','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.output'})
g.wasDerivedFrom('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/wc1P00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.output')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/c2P00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.output','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.output'})
g.wasDerivedFrom('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/c2P00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.output')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/mwc2P00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.output','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.output'})
g.wasDerivedFrom('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/mwc2P00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.output')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/wc2P00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.output','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.output'})
g.wasDerivedFrom('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/wc2P00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.output')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/c3P00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.output','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.output'})
g.wasDerivedFrom('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/c3P00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.output')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/mwc3P00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.output','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.output'})
g.wasDerivedFrom('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/mwc3P00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.output')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/wc3P00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.output','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.output'})
g.wasDerivedFrom('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/wc3P00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.output')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/mP00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.output','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.output'})
g.wasDerivedFrom('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/mP00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.output')
g.entity('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/P00004218_S0001_T1_1.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.data','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.data'})
g.used('/share/data/data10/CogRes_old/Subjects/P00004218/S0001/T1/P00004218_S0001_T1_1.nii','matlabbatch1.spm.spatial.preproc.data')
g.entity('/share/data/data5/spm8/tpm/csf.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.opts.tpm','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts.tpm'})
g.used('/share/data/data5/spm8/tpm/csf.nii','matlabbatch1.spm.spatial.preproc.opts.tpm')
g.entity('/share/data/data5/spm8/tpm/grey.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.opts.tpm','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts.tpm'})
g.used('/share/data/data5/spm8/tpm/grey.nii','matlabbatch1.spm.spatial.preproc.opts.tpm')
g.entity('/share/data/data5/spm8/tpm/white.nii',{'prov:label':'matlabbatch1.spm.spatial.preproc.opts.tpm','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts.tpm'})
g.used('/share/data/data5/spm8/tpm/white.nii','matlabbatch1.spm.spatial.preproc.opts.tpm')
g.entity('',{'prov:label':'matlabbatch1.spm.spatial.preproc.opts.msk','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.preproc.opts.msk'})
g.used('','matlabbatch1.spm.spatial.preproc.opts.msk')
with open('/Users/jason/Documents/ProvenanceTools/SPMprovenance/OutputFiles/SegmentONLYJob_FilledInJobRECURSIVE.provn', 'wt') as fp:fp.writelines(g.get_provn())
