import os
import sys
import datetime
from socket import gethostname
sys.path.append("/Users/jason/Documents/ProvenanceTools/prov")
import prov.model as prov
from prov.model import Namespace, PROV
EX=Namespace("ex","http://www.example.com/")
g = prov.ProvBundle()
g.entity('matlabbatch')
g.activity('spm.spatial.preproc')
g.used('matlabbatch','spm.spatial.preproc')
g.entity('data_1')
g.used('spm.spatial.preproc','data_1')
g.entity('output_1')
g.used('spm.spatial.preproc','output_1')
g.activity('spm.temporal.st')
g.used('matlabbatch','spm.temporal.st')
g.entity('scans_2')
g.used('spm.temporal.st','scans_2')
g.entity('nslices_2')
g.used('spm.temporal.st','nslices_2')
g.activity('spm.spatial.realign.estwrite')
g.used('matlabbatch','spm.spatial.realign.estwrite')
g.entity('data_3')
g.used('spm.spatial.realign.estwrite','data_3')
g.entity('eoptions_3')
g.used('spm.spatial.realign.estwrite','eoptions_3')
g.activity('spm.spatial.coreg.estimate')
g.used('matlabbatch','spm.spatial.coreg.estimate')
g.entity('ref_4')
g.used('spm.spatial.coreg.estimate','ref_4')
g.entity('source_4')
g.used('spm.spatial.coreg.estimate','source_4')
g.activity('spm.spatial.normalise.write')
g.used('matlabbatch','spm.spatial.normalise.write')
g.entity('subj_5')
g.used('spm.spatial.normalise.write','subj_5')
g.entity('roptions_5')
g.used('spm.spatial.normalise.write','roptions_5')
g.activity('spm.spatial.smooth')
g.used('matlabbatch','spm.spatial.smooth')
g.entity('data_6')
g.used('spm.spatial.smooth','data_6')
g.entity('fwhm_6')
g.used('spm.spatial.smooth','fwhm_6')
with open('/Users/jason/Documents/ProvenanceTools/SPMprovenance/OutputFiles/TestPreProcessSHORT_FilledInJob.provn', 'wt') as fp:fp.writelines(g.get_provn())
