import os
import sys
import datetime
from socket import gethostname
sys.path.append("/Users/jason/Documents/ProvenanceTools/prov")
import prov.model as prov
from prov.model import Namespace, PROV
EX=Namespace("ex","http://www.example.com/")
g = prov.ProvBundle()
g.entity('matlabbatch')
g.entity('matlabbatch1')
g.used('matlabbatch','matlabbatch1')
g.entity('matlabbatch1.spm',{'prov:type':'bundle','prov:label':'spm','spm:structpath':'matlabbatch1'})
g.used('matlabbatch1','matlabbatch1.spm')
g.entity('matlabbatch1.spm.spatial',{'prov:type':'bundle','prov:label':'spatial','spm:structpath':'matlabbatch1.spm'})
g.used('matlabbatch1.spm','matlabbatch1.spm.spatial')
g.entity('matlabbatch1.spm.spatial.normalise',{'prov:type':'bundle','prov:label':'normalise','spm:structpath':'matlabbatch1.spm.spatial'})
g.used('matlabbatch1.spm.spatial','matlabbatch1.spm.spatial.normalise')
g.entity('matlabbatch1.spm.spatial.normalise.write',{'prov:type':'bundle','prov:label':'write','spm:structpath':'matlabbatch1.spm.spatial.normalise'})
g.used('matlabbatch1.spm.spatial.normalise','matlabbatch1.spm.spatial.normalise.write')
g.entity('matlabbatch1.spm.spatial.normalise.write.subj',{'prov:type':'bundle','prov:label':'subj','spm:structpath':'matlabbatch1.spm.spatial.normalise.write'})
g.used('matlabbatch1.spm.spatial.normalise.write','matlabbatch1.spm.spatial.normalise.write.subj')
g.entity('matlabbatch1.spm.spatial.normalise.write.subj.matname',{'prov:type':'bundle','prov:label':'matname','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.subj'})
g.used('matlabbatch1.spm.spatial.normalise.write.subj','matlabbatch1.spm.spatial.normalise.write.subj.matname')
g.entity('matlabbatch1.spm.spatial.normalise.write.subj.resample',{'prov:type':'bundle','prov:label':'resample','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.subj'})
g.used('matlabbatch1.spm.spatial.normalise.write.subj','matlabbatch1.spm.spatial.normalise.write.subj.resample')
g.entity('matlabbatch1.spm.spatial.normalise.write.roptions',{'prov:type':'bundle','prov:label':'roptions','spm:structpath':'matlabbatch1.spm.spatial.normalise.write'})
g.used('matlabbatch1.spm.spatial.normalise.write','matlabbatch1.spm.spatial.normalise.write.roptions')
g.entity('matlabbatch1.spm.spatial.normalise.write.roptions.preserve',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.roptions','prov:label':'preserve','prov:value':'0'})
g.used('matlabbatch1.spm.spatial.normalise.write.roptions','matlabbatch1.spm.spatial.normalise.write.roptions.preserve')
g.entity('matlabbatch1.spm.spatial.normalise.write.roptions.bb',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.roptions','prov:label':'bb','prov:value':'[ -78 -112 -50; 78 76 85]'})
g.used('matlabbatch1.spm.spatial.normalise.write.roptions','matlabbatch1.spm.spatial.normalise.write.roptions.bb')
g.entity('matlabbatch1.spm.spatial.normalise.write.roptions.vox',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.roptions','prov:label':'vox','prov:value':'[ 2 2 2]'})
g.used('matlabbatch1.spm.spatial.normalise.write.roptions','matlabbatch1.spm.spatial.normalise.write.roptions.vox')
g.entity('matlabbatch1.spm.spatial.normalise.write.roptions.interp',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.roptions','prov:label':'interp','prov:value':'1'})
g.used('matlabbatch1.spm.spatial.normalise.write.roptions','matlabbatch1.spm.spatial.normalise.write.roptions.interp')
g.entity('matlabbatch1.spm.spatial.normalise.write.roptions.wrap',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.roptions','prov:label':'wrap','prov:value':'[ 0 0 0]'})
g.used('matlabbatch1.spm.spatial.normalise.write.roptions','matlabbatch1.spm.spatial.normalise.write.roptions.wrap')
g.entity('matlabbatch1.spm.spatial.normalise.write.roptions.prefix',{'prov:type':'spm:parameter','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.roptions','prov:label':'prefix','prov:value':'w'})
g.used('matlabbatch1.spm.spatial.normalise.write.roptions','matlabbatch1.spm.spatial.normalise.write.roptions.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/T1/T1_P00004218_S0001_seg_sn.mat',{'prov:label':'matlabbatch1.spm.spatial.normalise.write.roptions.prefix','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.roptions.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/T1/T1_P00004218_S0001_seg_sn.mat','matlabbatch1.spm.spatial.normalise.write.roptions.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/waECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.normalise.write.roptions.prefix','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.roptions.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/waECF_r1_P00004218_S0001.nii','matlabbatch1.spm.spatial.normalise.write.roptions.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/wmeanaECF_r1_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.normalise.write.roptions.prefix','prov:type':'ImageIndex','prov:value':'1','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.roptions.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r1/wmeanaECF_r1_P00004218_S0001.nii','matlabbatch1.spm.spatial.normalise.write.roptions.prefix')
g.entity('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/waECF_r2_P00004218_S0001.nii',{'prov:label':'matlabbatch1.spm.spatial.normalise.write.roptions.prefix','prov:type':'ImageIndex','prov:value':'[ 1 2 3 4 5 6 7 8 9 10]','spm:structpath':'matlabbatch1.spm.spatial.normalise.write.roptions.prefix'})
g.wasDerivedFrom('/share/data/studies/CogRes/Subjects/P00004218/S0001/ECF_r2/waECF_r2_P00004218_S0001.nii','matlabbatch1.spm.spatial.normalise.write.roptions.prefix')
